# Generated by Django 5.1.3 on 2024-11-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('image_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
